### ISSUE TITLE
Error instead of Panic

### ISSUE THREAD

**Issue by ayushr2** [dsoprea/go-ext4#3]
Currently go-ext4 panics on most of the errors paths. Think it would be worth returning an error (which the current code supports with return statements) so that client code can deal with the error as they like. Currently all errors returned from most functions are always nil.

This will allow flexibility in use. Client code can panic if they like or continue gracefully.

**Comment by dsoprea** [comment]
What is "errors paths"?

I'm not sure what you're referring to. The project is very strict in general and should *only* return a `nil` if no errors were encountered.

**Comment by dsoprea** [comment]
Please don't open issues unless you're able to cite specific problems/examples.

**Comment by ayushr2** [comment]
What I meant by error path is the code paths it takes when errors occur.

For instance, the usage of
```
log.PanicIf(err)
```
whenever an error is encountered. It would panic the app.

**Comment by ayushr2** [comment]
Currently a function would either:
- return with no error
- or panic

I am suggesting it should
- return with nil err when no error (like it does now)
- return a non-nil err when error occurs. the error can document the cause of the error. Then the user has the flexibility to do what they want about it.

**Comment by dsoprea** [comment]
The top of each function has defer-recover handling.

Read more about the "Defer-Recover-Panic" pattern in Go:

https://blog.golang.org/defer-panic-and-recover

**Comment by ayushr2** [comment]
It panics there too (after recovering). It uses `log.Panic(err)`

**Comment by ayushr2** [comment]
It would greatly simplify logic and work flow if we drop the panic recover model and simply return the errors.

**Comment by dsoprea** [comment]
The problem is that defer-recover-panic is good for also catching the errors that Go or unhandled errors that external libraries originate.. The errors that are caused due to failures that are outside of your control. It's simple enough if you know how it works. It makes sure that *all* panics are funneled down to a return value so that the caller can always check it. Things are simpler without it only until what you're doing gets more complicated, and then it becomes an indispensable safety net.

In additional, I have some error management that always makes sure that all non-primitive errors (e.g. io.EOF) always have a stacktrace attached to them. Even though Go-originated errors won't show a specific line-number where the error originated, we can *guarantee* that you'll at least be able to identify the function.

I've fixed the recover() blocks. That was a bug. There's no point to having them if you're just gonna panic anyway. Since you're generally just writing it once and then copying it to ever function, I had somehow missed that.

**Comment by twitchyliquid64** [comment]
Heya,

Just wondering if you would consider a PR to re-write the error handling logic as:

```go
if err := ...; err != nil {
  return fmt.Errorf("...context...: %v", err)
}
```

as opposed to panicking?

I get the desire to have a stack trace for each error, but it goes against [Effective Go](https://golang.org/doc/effective_go.html#errors) patterns + the overhead of `defer` is non-neglible for cpu-bound programs. I'm firmly in the camp that panic is for error conditions where crashing out the request / program is the ideal response (ie: OOM, bounds check failure, runtime inconsistencies).

That said, this is your project, so style conventions are your call.

**Comment by dsoprea** [comment]
I don't know if that's a reasonable argument. Please share a link supporting your claims.

The pattern is recommended in Effective Go right below where you shared and nowhere is there a footnote assigning a cost to defers. Ostensibly it can't be much more expensive than any other function call. That being the case, the current state of development encourages readability or reusability at the expense of a couple of extra cycles. The age when terse or indipherable programming ruled the land in the name of ultra-optimization to win every cycle we could was a long time ago. All systems are fast and cycles are abounding nowadays. No one is gonna argue for saving a couple of cycles (if what you say is true) by shaving a few defers.

The truth is that the panic-defer-recover pattern is there for a reason. It allows us to have a higher degree of control during both general operation and testing and a commensurate increase of quality as a result, which I happily embrace.

**Comment by twitchyliquid64** [comment]
My point about performance is minor; I'm mostly a fan of `error` types for handling errors for their readability and convention properties. I agree that readability > performance in most cases. 

> Ostensibly it can't be much more expensive than any other function call.

Nack, defers are tracked in their own structure in each frame, so they can be unwound when the function returns or panics. For the same reason, defers can't be inlined. (I deleted the rest of the stuff I wrote here once I looked at the code, as its changed a lot recently).

> Please share a link supporting your claims.

The relevant code is [here](https://github.com/golang/go/blob/726b1bf9871f4905d85a53051301f636e8273328/src/runtime/panic.go#L255) and below (see `newdefer`). This is actually been optimized a lot since I last looked at it.

Previously, every defer issued a write barrier, and needed to check+grow the stack in a lot of cases due to the defer frames. This overhead had quite a performance hit on hot paths, and a quick Google shows theres a few blog posts also [observing](https://medium.com/i0exception/runtime-overhead-of-using-defer-in-go-7140d5c40e32) their performance hit.

Now, it looks like most simple defers (like yours, with no arguments) can be allocated on the nosplit stack, and write barriers are eliminated, so the performance should be a lot better (just the overhead of handling the defer structure and running it). A quick look suggests [goreview/29656](https://go-review.googlesource.com/c/go/+/29656) & [goreview/171758](https://go-review.googlesource.com/c/go/+/171758/) are to thank. That said, this will still be wicked slow in _really_ hot code paths due to the lack of inlining.

> It allows us to have a higher degree of control during both general operation and testing

How?

In any case, how is

```go
defer func(){
  if e := recover(); ... {
    ...
  }
}

if <errorcheck> {
  panic(thing)
}
```
meaningfully different from

```go
if <errorcheck> {
   return nil, fmt.Errorf("context: %v", err)
}
```

The only upside I can see with the panic is the stack frame.
